spring.application.name=foodvoting

# Use port 8083 for local development to avoid conflicts with 8080
server.port=8083

# PostgreSQL DB setting
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=root1234

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
